import ContractDetail from "../pages/contract/ContractDetailPage";

export const ROUTES = {
  profile: "/profile",
  login: "/login",
  contracts: "/contracts",
  forgotPassword: "/forgot-password",
  verifyCode: "/verify-code",
  newPassword: "/new-password",
  changePassword: "/change-password",
  editProfile: "/edit-profile",
  tenantDetail: "/tenants/:id",
  tenants: "/tenants",
  createTenants: "/tenants/create",
  tenantEdit: "/tenants/:id/edit",
  bills: "/bills",
  billDetail: "/bills/:id",
  contractDetail: "/contracts/:id",
  contractAddendum: "/contracts/:id/addendum",
  createContract: "/contracts/create",
  receiveGuestRegistration: "/receive-guest",
  tenantCreate: "/tenants/create",
  notifications: "/notifications",
  createNotification: "/notifications/create",
  editNotification: "/notifications/:id/edit",
};
