export const ROUTES = {
  profile: "/profile",
  login: "/login",
  contracts: "/contracts",
  forgotPassword: "/forgot-password",
  verifyCode: "/verify-code",
  newPassword: "/new-password",
  changePassword: "/change-password",
  editProfile: "/edit-profile",
  tenantDetail: "/tenants/:id",
  tenants: "/tenants",
  tenantEdit: "/tenants/:id/edit",
  bills: "/bills",
  billDetail: "/bills/:id",
};
